{% set name = "nmma" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nmma-{{ version }}.tar.gz
  sha256: f82bf74f1bcbe97b6d9f36438fdc7c45a50d73edfd178adcb2f3f10645f17f35

build:
  entry_points:
    - nmma_analysis=nmma.pbilby.analysis:main
    - nmma_generation=nmma.pbilby.generation:main
    - nmma_gw_generation=nmma.pbilby.generation:main_nmma_gw
    - nmma_gw_analysis=nmma.pbilby.analysis:main_nmma_gw
    - parallel_em_analysis=nmma.pbilby.em_analysis:main
    - parallel_em_generation=nmma.pbilby.em_generation:main
    - light_curve_analysis=nmma.em.analysis:main
    - light_curve_injection_summary=nmma.em.injection_summary:main
    - light_curve_injection_slurm_setup=nmma.em.create_injection_slurm:main
    - light_curve_injection_condor_setup=nmma.em.create_injection_condor:main
    - lightcurve_marginalization=nmma.em.lightcurve_marginalization:main
    - light_curve_manual=nmma.em.manual:main
    - combine_EOS=nmma.em.combine_EOS:main
    - create_light_curve_slurm=nmma.em.create_lightcurves_slurm:main
    - create_light_curve_condor=nmma.em.create_lightcurves_condor:main
    - create_svdmodel=nmma.em.create_svdmodel:main
    - svdmodel_benchmark=nmma.em.svdmodel_benchmark:main
    - light_curve_generation=nmma.em.create_lightcurves:main
    - light_curve_detection=nmma.em.detect_lightcurves:main
    - nmma_create_injection=nmma.eos.create_injection:main
    - gwem_resampling=nmma.em.gwem_resampling:main
    - gwem_resampling_condor=nmma.em.gwem_resampling_condor:main
    - gwem_Hubble_estimate=nmma.em.gwem_Hubble_estimate:main
    - light_curve_analysis_condor=nmma.em.analysis_condor:main

  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - arviz
    - astropy >=4.3.1
    - bilby >=1.2.0
    - bilby_pipe >=1.1.0
    - colorcet
    - corner
    - dust_extinction
    - dynesty
    - future
    - gwpy
    - healpy
    - h5py
    - joblib
    - lal
    - lalsimulation
    - ligo.skymap
    - ligo-followup-advocate
    - matplotlib-base >=2.0
    - mpi4py
    - nestcheck
    - numpy >=1.9
    - pandas >=1.3.4
    - parallel-bilby
    - p-tqdm
    - pymultinest
    - python >=3.7
    - pyyaml
    - requests
    - scikit-learn >=1.0.2
    - scipy >=1.7.1
    - seaborn
    - sncosmo
    - tqdm

test:
  imports:
    - nmma
  commands:
    - pip check
    - light_curve_analysis --help
    - light_curve_injection_summary --help
    - light_curve_injection_slurm_setup --help
    - light_curve_injection_condor_setup --help
    - lightcurve_marginalization --help
    - combine_EOS --help
    - create_light_curve_slurm --help
    - create_light_curve_condor --help
    - create_svdmodel --help
    - light_curve_generation --help
    - light_curve_detection --help
    - nmma_create_injection --help
    - gwem_resampling --help
    - gwem_resampling_condor --help
    - gwem_Hubble_estimate --help
    - light_curve_analysis_condor --help
  requires:
    - pip
    - mpi4py
    - nestcheck

about:
  home: https://github.com/nuclear-multimessenger-astronomy/nmma
  summary: A nuclear physics multi-messenger Bayesian inference library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sahiljhawar
    - mcoughlin
